// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOVqO3_gOO2kcNsydzNhmjFB79MZxE8Rs',
    appId: '1:282198273530:web:7a8bd14437523a5f938843',
    messagingSenderId: '282198273530',
    projectId: 'mindmark-29a52',
    authDomain: 'mindmark-29a52.firebaseapp.com',
    storageBucket: 'mindmark-29a52.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKiQfe4GO1g12Fje4TC8rPNwYg-tjr1zE',
    appId: '1:282198273530:android:e53aae62b235b0c3938843',
    messagingSenderId: '282198273530',
    projectId: 'mindmark-29a52',
    storageBucket: 'mindmark-29a52.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxoX0mK0Y8L5HDgLdrxoXizVXjHiUfeyk',
    appId: '1:282198273530:ios:84c57105eda75314938843',
    messagingSenderId: '282198273530',
    projectId: 'mindmark-29a52',
    storageBucket: 'mindmark-29a52.appspot.com',
    iosBundleId: 'com.example.mindmark',
  );
}
